data/config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :confirmations => 'users/confirmations',
    :passwords => 'users/passwords'
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  resources :users, :only => [:show, :create, :edit, :update, :destroy]
  resources :wallets, :only => [:index, :show, :create, :destroy]
  resource :two_factor_auth, only: [:new, :create, :destroy]

  get 'wallet', :controller => "users", :actoin => "wallet"
  get 'transfer', :controller => "users", :action => "transfer"
  post 'transfer_done', :controller => "users", :action => "transfer_done"
end

data/app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="container">
      <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
        <h2>Ethfy</h2>
      </div>
      <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
          <ul>
            <li style="font-weight: bold;">Products</li>
            <li>Buy/Sell Ethreum</li>
            <li>Wallet</li>
          </ul>
        </div>
        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
          <ul>
            <li style="font-weight: bold;">Learn</li>
            <li>Whar is Ehtereum?</li>
            <li>hogehoge</li>
          </ul>
        </div>
        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
          <ul>
            <li style="font-weight: bold;">Company</li>
            <li>Abount</li>
            <li>Press</li>
            <li>Legal & privacy</li>
          </ul>
        </div>
        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
          <ul>
            <li style="font-weight: bold;">Social</li>
            <li>Blog</li>
            <li>Twitter</li>
            <li>Facebook</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
      <hr>
      <div>
        <p><small>Copyright &copy; 2016 Sendee INC. ALL Rights Reserves.</small></p>
      </div>
    </div>
</footer>

data/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <%= link_to "Ethfy", '/', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Etherを受け取る", "/wallet" %></li>
        <li><%= link_to "Etherを送る", "/transfer" %></li>
        <li>1Ehter = ¥<%=  %></li>
        <% if user_signed_in? %>
          <li><%= current_user.email %></li>
          <li><%=  %></li>
          <li><%= link_to "ユーザー情報の変更", edit_user_registration_path %></li>
          <li><%= link_to "ログアウト", sign_out_path %></li>
        <% else %>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

data/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Main</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
<body>
<%= render 'layouts/header' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>